apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: gvs2wux6h-go 
  janus-idp.io/tekton: gvs2wux6h-go
  backstage.io/kubernetes-id: gvs2wux6h-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: gvs2wux6h-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  