apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: gvs2wux6h-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: gvs2wux6h-go 
  name: gvs2wux6h-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: gvs2wux6h-go 
